### ISSUE TITLE
getLastCookieContent方法在php8.0中无法正常使用

### ISSUE THREAD

**Issue by heihuo8** [Zjmainstay/php-curl#1]
getLastCookieContent方法在php8.0中无法正常使用

**Comment by Zjmainstay** [comment]
> getLastCookieContent方法在php8.0中无法正常使用

这个方法只是获取cookie写入临时文件的内容，应该不存在版本兼容性，你可以打开一下错误日志看看是否cookie文件写入失败导致最终获取失败。

error_reporting(E_ALL);
ini_set('display_errors', 1);

**Comment by Zjmainstay** [comment]
tempnam方法前面加了@，无法及时报错提示，已删除。
